# apiVersion: v1
# kind: Pod
# metadata:
#   name: resources
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     resources:
#       requests:
#         # soft limit 
#         cpu: "100m"
#         memory: "128m"
#       limits:
#         # hard limit
#         cpu: "200m"
#         memory: "256mi"    

apiVersion: v1
kind: Pod
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
