apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
data:
  username: Y2hhbmR1Cg==
  password: Q2hhbmR1QDEyMwo=

--- # we are using another resource
# we are refering all the secrets here
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: nginx
    envFrom:
    - secretRef:
        name: secret-basic-auth
  
